server:
  port: 8888

management:
  security:
    enabled: false

spring:
  application:
    name: config-server
  profiles:
    include: native # required to use native search-paths
  cloud:
    bus:
      enabled: true
    config:
      server:
        native:
          search-locations: file:/config-repo
        # git:
        #   uri: https://github.com/panga/unibave-microservices.git
        #   search-paths: sources/complete/config-repo        
  rabbitmq:
    host: localhost
    port: 5672    
    
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672